int ques0(int x, int y);
int ans0(int x, int y);

int ques_badger(int x);
int ques_highland_cow(int x);
int ques_iguana(int x);
int ques_burro(void);
int ques_ground_hog(int x);
int ques_alpaca(int x);
int ques_canary(int x, int y);
int ques_ferret(int x);
int ques_finch(int x, int n, int c);
int ques_shrew(int x);
int ques_pony(int x);
int ques_whale(int x);
int ques_chinchilla(int x);
int ques_porcupine(int x, int m, int n);
int ques_porpoise(int x, int n);
int ans_badger(int x);
int ans_highland_cow(int x);
int ans_iguana(int x);
int ans_burro(void);
int ans_ground_hog(int x);
int ans_alpaca(int x);
int ans_canary(int x, int y);
int ans_ferret(int x);
int ans_finch(int x, int n, int c);
int ans_shrew(int x);
int ans_pony(int x);
int ans_whale(int x);
int ans_chinchilla(int x);
int ans_porcupine(int x, int m, int n);
int ans_porpoise(int x, int n);
